import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header"
import Footer from '../components/Footer'


export const metadata: Metadata = {
  title: "Jessica's portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" type="image/png" href="/icon.png" />
      </head>
      <body className="bg-white text-black flex flex-col min-h-screen">
        <Header />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
