import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header"
import Footer from '../components/Footer'


export const metadata: Metadata = {
  title: "Jessica's portfolio",
  description: "Generated by create next app",
  icons: {
  icon: "/favicon.ico"
}
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Jessica's Portfolio</title>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="bg-white text-black flex flex-col min-h-screen">
        <Header />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
